import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  white: {
    backgroundColor: 'white',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
  },
  red: {
    backgroundColor: 'red',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  blue: {
    backgroundColor: 'blue',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  green: {
    backgroundColor: 'green',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomRightRadius: 16,
    borderTopRightRadius: 16,
  },
  alignCheck: {
    alignItems: 'center',
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
  },
  title: {
    width: '100%',
    borderWidth: 1,
    borderColor: 'grey',
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  desc: {
    padding: 16,
    width: '100%',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 8,
    backgroundColor: '#fff',
    marginTop: 16,
    marginBottom: 16,
  },
  containerColor: {
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    height: 50,
    borderWidth: 1,
    borderColor: 'black',
    flexDirection: 'row',
  },
  input: {
    height: 50,
    borderWidth: 1,
    width: 50,
    borderRadius: 8,
    marginVertical: 16,
  },
});
